export default {
  entry: [
    "sh/bench/*.js",
    "dev.js",
    "minify.js",
    "extract/run.js",
    "sh/check.js",
    "sh/stringAnalyze.js",
    "sh/unicodeUnescape.js",
    "test/compare.test.js",
    "plugin/serve.js",
    "plugin/markdown-it/src/index.js",
    "plugin/markdown-it/test.js",
    "plugin/marked/src/index.js",
    "plugin/marked/test.js",
    "plugin/remark/src/index.js",
    "plugin/remark/test.js",
    "sh/bench/self.js",
    "sh/compile_i18n.js",
    "sh/gen_formula_svg.js",
  ],
  ignore: ["demo/**", "lib/**", "plugin/*/lib/**", "plugin/*/src/*.d.ts", "./conf/**"],
  ignoreDependencies: [
    "@mathjax/mathjax-mhchem-font-extension",
    "oxfmt",
    "oxlint",
    "@1-/mdcheck",
    "@1-/mdimg2cdn",
  ],
};
