const FORMULAS = [
  "e^{i\\pi} + 1 = 0",
  "E = m \\cdot c^2",
  "\\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}",
  "\\sum_{n=1}^{\\infty} \\frac{1}{n^2} = \\frac{\\pi^2}{6}",
  "\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}",
  "\\left( \\sum_{i=1}^n a_i \\cdot b_i \\right)^2 \\le \\left( \\sum_{i=1}^n a_i^2 \\right) \\cdot \\left( \\sum_{i=1}^n b_i^2 \\right)",
  "\\overline{A \\cup B} = \\overline{A} \\cap \\overline{B}",
  "\\bar{x} = \\frac{1}{n} \\cdot \\sum_{i=1}^n x_i",
  "x = \\frac{-b \\pm \\sqrt{b^2 - 4 \\cdot a \\cdot c}}{2 \\cdot a}",
  "\\frac{a + b}{c + \\frac{d}{e}}",
  "\\log(a \\cdot b) = \\log a + \\log b",
  "a^2 + b^2 = c^2",
  "\\sin x = x - \\frac{x^3}{6} + \\frac{x^5}{120}",
  "\\frac{\\alpha_1}{\\beta_1 + \\frac{\\alpha_2}{\\beta_2 + \\frac{\\alpha_3}{\\beta_3}}}",
  "\\alpha_{i_j}^{2^k} + \\beta_{x_y}^{3^z} \\ge \\gamma_{a_b}^{n^m}",
  "\\sqrt[3]{a \\cdot b \\cdot c}",
  "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}",
  "|x| = \\begin{cases} x & x \\ge 0 \\\\ -x & x < 0 \\end{cases}",
  "\\left. \\frac{df}{dx} \\right| _0",
  "\\forall x \\in A \\Rightarrow x \\notin B \\Leftrightarrow A \\cap B = \\emptyset",
  "\\cos^2 x + \\sin^2 x = 1",
  "1 + 2 + \\cdots + n = 0.5 \\cdot n \\cdot (n + 1)",
  "\\left( x",
  "\\lim_{n \\to \\infty} \\left(1 + \\frac{1}{n}\\right)^n = e",
  "f(x) = x \\quad \\text{if } x > 0",
  "\\ln(x) + \\det(A) - \\arcsin(y)",
  "a \\pm b \\equiv c \\pmod m",
  "f(x) = \\cot(x) \\cdot \\sec(x) \\cdot \\csc(x)",
  "\\boxed{x^2 + y^2 = z^2}",
  "\\cancel{x - y}",
  "\\sum\\limits_{i=1}^n i",
  "\\phantom{x} + y",
  "\\hat{h}_U[n] = \\mathbf{W} \\mathbf{x}[n] + \\tilde{\\mathbf{e}}",
  "P(w_i \\mid w_{1:i-1}) = \\dfrac{P(w_1, \\dots, w_i)}{P(w_1, \\dots, w_{i-1})}",
  "\\mathcal{H}_A \\otimes \\mathcal{H}_B \\oplus \\mathbb{C}^n",
  "\\iint_D \\rho(r, \\varphi) dr d\\varphi \\quad (r \\ll R, \\theta = 45\\degree)",
  "\\prod_{k=2}^n \\left(1 - \\frac{1}{k^2}\\right) \\stackrel{n \\to \\infty}{\\longrightarrow} \\frac{1}{2}",
  "\\Delta H_{\\rm rxn}^\\circ = -R T \\ln K \\quad \\textrm{where } \\mathrm{const} > 0",
  "a_n \\uparrow a, \\, b_n \\downarrow b \\Rightarrow (f \\circ g)(x) \\bullet y \\lt 1 \\tag{1}",
];

export default FORMULAS;
